### ISSUE TITLE
Different cost functions

### ISSUE THREAD

**Issue by teng-gao** [zdebruine/RcppML#48]
Hi!

Is it possible to set a different cost function instead of Frobenius norm?

For example, a Poisson cost or KL: https://pubmed.ncbi.nlm.nih.gov/15016911/

**Comment by zdebruine** [comment]
This is something we've thought about but not done.  We definitely thought about KL, and I do have some scratch code on that, but it was 30x slower and really didn't do as well for any of our work, so it never made it into the main repo.  You may wish to rig up NMF in keras if you want to do different cost functions.

**Comment by teng-gao** [comment]
Gotcha, thanks for the quick answer!
