### ISSUE TITLE
`SparseMatrix::t()` doesn't work unless Matrix is fully attached

### ISSUE THREAD

**Issue by DavisVaughan** [zdebruine/RcppML#5]
In a fresh R session:

``` r
library(modeldata)
data("Chicago")

df <- Chicago[, c("Austin", "Quincy_Wells")]
x <- t(as.matrix(df))
x <- Matrix::Matrix(x, sparse = TRUE)

RcppML::nmf(
  A = x,
  k = 7,
  L1 = c(0.001, 0.001), 
  verbose = FALSE, 
  seed = 86021L, 
  nonneg = TRUE
)
#> Error in RcppML::nmf(A = x, k = 7, L1 = c(0.001, 0.001), verbose = FALSE, : Cannot convert object to an environment: [type=character; target=ENVSXP].
```

If you `library(Matrix)`, then it works.

The problem is with this line here:
https://github.com/zdebruine/RcppML/blob/134be7ee56790138f55c3ec871f77442252853e7/inst/include/RcppML/SparseMatrix.hpp#L82

It can't seem to lookup the Matrix package, so it returns the error from above.

I'm not entirely sure how Rcpp::Environment works, but I assume it is trying to find that environment on the search path, as returned by `search()`, which only lists fully attached packages (rather than loaded ones). I think Matrix will be loaded, but not fully attached, so it can't find it.

**Comment by zdebruine** [comment]
Fixed, and thanks!  Install the new GH version (0.3.6, patched up from 0.3.5) and Rcpp will load the `Matrix` namespace environment as long as the `Matrix` package is installed, which should generally be the case because `Matrix` is imported by `RcppML`.

I needed to use `Rcpp::Environment::namespace_env()` instead of `Rcpp::Environment` to look beyond the paths strictly returned by `search()`.

**Comment by topepo** [comment]
Thanks. 

In case you are interested, we are using this package in one of our packages ([`recipes`](https://www.tmwr.org/recipes.html)). We have another function, [`step_nnmf()`](https://recipes.tidymodels.org/reference/step_nnmf.html) that uses the NMF package (which has some issues). Yours is 541-fold faster (I'm not kidding) from my benchmarking so that's nice 😄

**Comment by zdebruine** [comment]
@topepo That's awesome!  `recipes` will likely benefit from specializations for dense matrices soon to come (just be deliberate about the class of your input matrix).  I'm committed to making this NMF implementation a non-breaking go-to option for R and C++ users.  If you have any relevant suggestions or feature requests, please share!

Yes, `NMF` package functions are very slow, but there are other sparse recommenders available in R that can be reduced to basic NMF (i.e., `rsparse::WRMF`, `cmfrec::CMF`).  These are very good implementations and come close to the `RcppML::nmf` runtime, but I am able to consistently learn better models (as measured by MSE) in less time across platforms and datasets.

**Comment by topepo** [comment]
> @topepo That's awesome! recipes will likely benefit from specializations for dense matrices soon to come (just be deliberate about the class of your input matrix). I'm committed to making this NMF implementation a non-breaking go-to option for R and C++ users. If you have any relevant suggestions or feature requests, please share!

That all sounds great; we appreciate. We generally have dense matrices but `textrecipes` represents the data sparsely.

**Comment by topepo** [comment]
Hey any progress on a new version? We'd love to replace NMF with this.

**Comment by zdebruine** [comment]
@topepo Yes, the new version with dense specialization has been stable on CRAN for quite some time!

The dev version moves from S3 to S4, with `$` accessors for all classes to ensure backwards compatibility.  The dev version also has a lot of new functionality (cross-validation, weighting, masking, joint NMF, etc.).  I also have a divisive clustering and a k-means clustering implementation ready to ship that beats anything I can find to test against.

**Comment by topepo** [comment]
That's great. For some reason, I didn't think that these changes made it into that version.
