### ISSUE TITLE
error in installing devtools::install_github("zdebruine/RcppML")

### ISSUE THREAD

**Issue by Rose-Hedderman** [zdebruine/RcppML#51]
> devtools::install_github("zdebruine/RcppML")
Using GitHub PAT from the git credential store.
Downloading GitHub repo zdebruine/RcppML@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                       
2: CRAN packages only        
3: None                      
4: xfun (0.42 -> 0.43) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 1
xfun (0.42 -> 0.43) [CRAN]
Installing 1 packages: xfun
trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.3/xfun_0.42.tgz'
Content type 'application/x-gzip' length 475932 bytes (464 KB)
==================================================
downloaded 464 KB

The downloaded binary packages are in
	/var/folders/xf/8l51mcd939x_wh_596kx9lpw0000gn/T//RtmpSU7Lxl/downloaded_packages
── R CMD build ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/xf/8l51mcd939x_wh_596kx9lpw0000gn/T/RtmpSU7Lxl/remotes5088378f0bf2/zdebruine-RcppML-5449a5b/DESCRIPTION’ ...
─  preparing ‘RcppML’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in
     serialize/load version 3 cannot be read in older versions of R.
     File(s) containing such objects:
       ‘RcppML/data/aml.rdata’ ‘RcppML/data/hawaiibirds.rdata’
       ‘RcppML/data/movielens.rdata’
─  building ‘RcppML_0.5.6.tar.gz’
   
* installing *source* package ‘RcppML’ ...
** using staged installation
** libs
using C++ compiler: ‘Apple clang version 15.0.0 (clang-1500.3.9.4)’
using C++11
using SDK: ‘MacOSX14.4.sdk’
clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include/ -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include    -DEIGEN_INITIALIZE_MATRICES_BY_ZERO -DEIGEN_NO_DEBUG -fPIC  -falign-functions=64 -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:
In file included from ./../inst/include/RcppML.h:13:
../inst/include/RcppML/SparseMatrix.h:96:63: warning: private field 's_size' is not used [-Wunused-private-field]
        int col_, index, max_index, s_max_index, s_index = 0, s_size;
                                                              ^
1 warning generated.
clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include/ -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include    -DEIGEN_INITIALIZE_MATRICES_BY_ZERO -DEIGEN_NO_DEBUG -fPIC  -falign-functions=64 -Wall -g -O2  -c RcppFunctions.cpp -o RcppFunctions.o
In file included from RcppFunctions.cpp:9:
./../inst/include/RcppML/SparseMatrix.h:96:63: warning: private field 's_size' is not used [-Wunused-private-field]
        int col_, index, max_index, s_max_index, s_index = 0, s_size;
                                                              ^
1 warning generated.
clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include/ -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include    -DEIGEN_INITIALIZE_MATRICES_BY_ZERO -DEIGEN_NO_DEBUG -fPIC  -falign-functions=64 -Wall -g -O2  -c bipartiteMatch.cpp -o bipartiteMatch.o
clang++ -arch arm64 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o RcppML.so RcppExports.o RcppFunctions.o bipartiteMatch.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/opt/gfortran/lib/gcc/aarch64-apple-darwin20.0/12.2.0 -L/opt/gfortran/lib -lgfortran -lemutls_w -lquadmath -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: search path '/opt/gfortran/lib/gcc/aarch64-apple-darwin20.0/12.2.0' not found
ld: warning: search path '/opt/gfortran/lib' not found
ld: library 'gfortran' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [RcppML.so] Error 1
ERROR: compilation failed for package ‘RcppML’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppML’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppML’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/xf/8l51mcd939x_wh_596kx9lpw0000gn/T//RtmpSU7Lxl/file508859f9f10d/RcppML_0.5.6.tar.gz’ had non-zero exit status

any thoughts on how to solve this?

**Comment by zdebruine** [comment]
Sounds like you need to install `gfortran`.  I'm guessing you're on a linux HPC system and you just need to load a module or contact your system administrator.  This is not an issue with the package, you will have issues installing many packages, particularly those depending on he `RcppEigen` package.
