### ISSUE TITLE
RcppML::nnls in Rcpp function?

### ISSUE THREAD

**Issue by MikeDMorgan** [zdebruine/RcppML#57]
Hi, I'd like to use your NNLS implementation in an Rcpp function, however, I'm not sure how to access the NNLS function. If try to export via RcppML::nnls it's not found in the namespace, nor does using `#include RcpML/nnls.hpp` directly.  I can see that the RcppML.hpp file only has `#include` statements for Rcpp_eigenbits.h and RcppML/SparseMatrix.h, which suggest nnls isn't in the RcppML namespace in C++.

Am I missing something obvious here?

**Comment by zdebruine** [comment]
Yeah, I could be better about the function naming convention here.  The NNLS function is in the RcppML/nnls.hpp on line 17 as `c_nnls()`.  It will be an in-place modify on Eigen matrices.

As far as includes go, you'll need to include `RcppMLCommon.hpp` which will pull in `RcppML/nmf.hpp` which will pull in `RcppML/predict.hpp` which will pull in `RcppML/nnls.hpp`.

Does that help?  I didn't expect folks to be interested in the actual solver...

**Comment by MikeDMorgan** [comment]
That's super helpful, thanks.  I'm using this for some constrained optimisation in a mixed effect model, and need something working and robust - this does the trick perfectly!
