### ISSUE TITLE
Feature request: online/streaming NMF

### ISSUE THREAD

**Issue by adarshk0** [zdebruine/RcppML#58]
Hi Zach,

Wondering if there are any plans to implement a streaming/online version of NMF to handle matrices that are too large to fit into memory? For context, I currently have a ``7e3 x 5e6`` matrix that I'd like to run ``RcppML::nmf`` on.

Cheers,
Adarsh

**Comment by zdebruine** [comment]
Hello Adarsh,

Super reasonable request...  You could do this yourself by running just one iteration of the model and feeding one submatrix at a time, and repeating the process for some number of iterations.  

```
# each file points to a .RDS with a dgCMatrix or matrix
matrix_filepaths <- list()

# initialize w
for(iter in 1:max_iter){
  w <- matrix(runif(nrow * k), nrow, k)
  for(file in matrix_filepaths){
     data_chunk <- readRDS(file)
     h <- RcppML::project(w, data_chunk)
     new_w <- RcppML::project(w, t(data_chunk))
     w <- w + learning_rate * new_w
  }
}
# w is your basis matrix.  You can project out to get h for all your submatrices
```

Code not tested.  I haven't implemented this in the package as R is notoriously horrible for streaming data structures out-of-core, and this implementation is definitely not as efficient.  Note that the larger your chunk size the faster global convergence would be achieved.  Generally folks doing this would be on the C++ end.

There are several algorithms for streaming NMF.  This may not be the best of them...

-Zach

**Comment by adarshk0** [comment]
Awesome! Much appreciated!
